### ISSUE TITLE
Documentation for iFrameProps.selectorId incorrect

### ISSUE THREAD

**Issue by jc5826** [bluejeans/webrtc-embed-sdk#1]
Please provide the original source code.  It would be much more helpful if the full non-minimized/obfuscated source is provided. 

The documentation sample code has   
`
BJNEmbedSDK.joinMeeting({
    meetingInfo: {
        meetingId: "1234556789",
        passcode: "1111"
    },
    iFrameProps: {
        selectorId: 'bluejeans_holder'
    },
    uiProps: {}
})
`

that should instead be `selectorId: '#bluejeans_holder'` for it to work.

With the combination of the documentation being incomplete/incorrect and the sample source code being unavailable, it has made getting started very difficult.

**Comment by naveenkbhaskar** [comment]
Thank you for your feedback. As you mentioned selectorId should be `selectorId: '#bluejeans_holder'`. We are working towards creating better documentation. will keep you posted on all the developments.

**Comment by naveenkbhaskar** [comment]
@jc5826 source code for sample app is added to the repo in 'sample-app' folder. Steps to get the sample app working is listed in the documentation. Please do take a look.
