### ISSUE TITLE
Mute Video and Audio button listeners appear swapped

### ISSUE THREAD

**Issue by chrismahoney** [bluejeans/webrtc-embed-sdk#2]
When clicking Mute Video or Mute Audio buttons, the button text and a/v state seem to operate in opposite fashion; i.e. clicking 'Mute Audio' mutes video and changes video button text to 'UnMute Video'.

**Comment by naveenkbhaskar** [comment]
@chrismahoney Thanks for reporting the issue. Swapped video and audio buttons on sample app is now fixed.
