### ISSUE TITLE
Name with space adds %20 for space

### ISSUE THREAD

**Issue by edot-richard** [bluejeans/webrtc-embed-sdk#3]
Hi,

When i pass a name with space in Webrtc parameters, it adds %20 for the space. Please check attached screenshot.

![image](https://user-images.githubusercontent.com/64777982/94891188-04192500-049f-11eb-9ae5-57eab8ae9947.png)

**Comment by renegadephantom** [comment]
@edot-richard  Thanks for reporting. We are looking into this issue.

**Comment by timfor** [comment]
@renegadephantom Any update on this issue?

**Comment by edoteee** [comment]
@renegadephantom Any update on this issue?

**Comment by grihan6** [comment]
This has been fixed.
