### ISSUE TITLE
Is it possible to set the email address of the participant?

### ISSUE THREAD

**Issue by owenl131** [bluejeans/webrtc-embed-sdk#6]
Is it possible to set the email address of the participant or any unique identifier to prevent the same user from joining multiple times?

**Comment by grihan6** [comment]
Hi,
It is currently not possible to prevent a user to join from multiple endpoints.
I'm curious on why you want to restrict a user with joining only once? Is there an issue that you face during the call?

**Comment by owenl131** [comment]
Hi, I was thinking more of preventing users from accidentally opening a meeting twice on the same device, which could potentially waste resources and degrade their meeting experience. But I can see your point about not really being able to differentiate the same user joining from different devices.

**Comment by grihan6** [comment]
Right and there are valid scenarios where a user might want to join from different browsers of different devices. Moreover, the moderator can always pitch in to check with the user who has joined twice.
Is this thread good to close?
