### ISSUE TITLE
Ability to Hide Drop Everyone when Ending the Bluejeans Calls

### ISSUE THREAD

**Issue by edoteee** [bluejeans/webrtc-embed-sdk#7]
Hello Support, 

Is it possible to hide the "Drop Everyone" dropdown when ending a Bluejeans call.

**Comment by grihan6** [comment]
Hi,
In my understanding, "Drop Everyone" is a checkbox and not a dropdown.
It's currently not configurable to hide. I'm curious on why you wish to hide "Drop Everyone" checkbox?

**Comment by edoteee** [comment]
We have users with the BlueJeans Moderator Role in the system, but they not quite familiar with the technology and rights that come with it.

So we don't want them to have a provision to drop the attendees (by mistake) during the live session.
Otherwise it will lead to losses to our clients.

**Comment by grihan6** [comment]
It somehow missed my attention.

I see. To understand user behaviour better, you are saying that these users "unknowingly" selected "Drop Everyone" before leaving the meeting? 

Does these users have access to moderator passcode of the meeting and they join using it? If yes - 1 simple way could be to provide "participant passcode" to users who should be just the participant & and they automatically would not have access to moderator controls like "Drop Everyone".

But, even if we have to think about role based access, do you want to selectively hide "Drop Everyone" for users with moderator role or for all moderators? I'm assuming that you would want at-least 1 moderator to have this control, right?

**Comment by edoteee** [comment]
> understand user behaviour better, you are saying that these users "unknowingly" selected "Drop Everyone" before leaving the meeting?

Yes

> Does these users have access to moderator passcode of the meeting and they join using it? If yes - 1 simple way could be to provide "participant passcode" to users who should be just the participant & and they automatically would not have access to moderator controls like "Drop Everyone".

Yes we have followed this approach for now.
